services:
  jaica-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      jaica-backend:
        condition: service_healthy

  jaica-backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://jaica-neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: qwerty
      CHROMA_HOST: jaica-chromadb
      CHROMA_PORT: 8000
      OLLAMA_HOST: http://host.docker.internal:11434
    depends_on:
      jaica-neo4j:
        condition: service_healthy
      jaica-chromadb:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/status" ]
      interval: 20s
      timeout: 5s
      retries: 5

  jaica-neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"   # HTTP (Neo4j Browser)
      - "7687:7687"   # Bolt protocol
    environment:
      NEO4J_AUTH: "neo4j/qwerty"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_memory_pagecache_size: "512M"
      NEO4J_dbms_memory_heap_max__size: "1G"
      NEO4J_dbms_security_auth__minimum__password__length: 4
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7474" ]
      interval: 10s
      timeout: 5s
      retries: 10

  jaica-chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"   # map host 8001 â†’ container 8000
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  chroma_data:
